// All Pins Description Table 
static PIN_DESC table_pin_desc[] = { 
    {GPIOC_0_IO_DATA_0, {{ "GPIOC_0_IO_DATA[0]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[0]"}, {"UARTC_0_I_SDA"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_1, {{ "GPIOC_0_IO_DATA[1]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[1]"}, {"UARTC_0_O_SDA"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_2, {{ "GPIOC_0_IO_DATA[2]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[2]"}, {"UARTC_2_I_SDA"}, {"UARTC_0_I_nCTS"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_3, {{ "GPIOC_0_IO_DATA[3]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[3]"}, {"UARTC_2_O_SDA"}, {"UARTC_0_O_nRTS"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_4, {{ "GPIOC_0_IO_DATA[4]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[4]"}, {"UARTC_1_I_SDA"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_5, {{ "GPIOC_0_IO_DATA[5]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[5]"}, {"UARTC_1_O_SDA"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_6, {{ "GPIOC_0_IO_DATA[6]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[6]"}, {"UARTC_3_I_SDA"}, {"UARTC_1_I_nCTS"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_7, {{ "GPIOC_0_IO_DATA[7]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[7]"}, {"UARTC_3_O_SDA"}, {"UARTC_1_O_nRTS"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_8, {{ "GPIOC_0_IO_DATA[8]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_CLK"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_9, {{ "GPIOC_0_IO_DATA[9]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[8]"}, {"UARTC_4_I_SDA"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_10, {{ "GPIOC_0_IO_DATA[10]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[9]"}, {"UARTC_4_O_SDA"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_11, {{ "GPIOC_0_IO_DATA[11]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[10]"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_12, {{ "GPIOC_0_IO_DATA[12]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[11]"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_13, {{ "GPIOC_0_IO_DATA[13]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[12]"}, {"N/A"}, {"SSIC_3_O_nSEL"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_14, {{ "GPIOC_0_IO_DATA[14]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[13]"}, {"N/A"}, {"SSIC_3_O_TXD}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_15, {{ "GPIOC_0_IO_DATA[15]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[14]"}, {"I2CC_2_IO_SCL "}, {"SSIC_3_O_BCLK"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_16, {{ "GPIOC_0_IO_DATA[16]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_DATA[15]"}, {"I2CC_2_IO_SDA"}, {"SSIC_3_I_RXD"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_17, {{ "GPIOC_0_IO_DATA[17]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_HSYNC"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {GPIOC_0_IO_DATA_18, {{ "GPIOC_0_IO_DATA[18]", 0, 0, 0, 24 }, {"VIC_I_DEV_1_VSYNC"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {IRDAC_IB_SDA, {{"N/A"{ "GPIOC_0_IO_DATA[0]", 0, 0, 0, 24 }}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_0_IB_CARD_nDETECT, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_0_IB_CARD_WRITE_PRT, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_0_IO_CMD, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_0_IO_DATA_0, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_0_IO_DATA_1, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_0_IO_DATA_2, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_0_IO_DATA_3, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_1_IO_CMD, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_1_IO_DATA_0, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_1_IO_DATA_1, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_1_IO_DATA_2, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_1_IO_DATA_3, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_0_IB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_0_OB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_2_IB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_2_OB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_1_IB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_1_OB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_3_IB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_3_OB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_4_IB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {UARTC_4_OB_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_RXER, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_RXDV, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_RXD_0, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_RXD_1, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_RXD_2, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_RXD_3, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_OB_TXEN, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_OB_TXD_0, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_OB_TXD_1, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_OB_TXD_2, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_OB_TXD_3, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_OB_MDC, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IO_MD, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_COL, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_CRS, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {CA5U_IB_DBG_TCK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {CA5U_IB_DBG_TMS, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {CA5U_IB_DBG_TDI, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {CA5U_IB_DBG_nTRST, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {CA5U_OB_DBG_TDO, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MM3101_I_DBG_nRST, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MM3101_I_DBG_TCK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MM3101_I_DBG_TDI, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MM3101_I_DBG_TMS, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MM3101_O_DBG_TDO, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_0_O_nSEL_1, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_0_O_nSEL_0, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_0_O_TXD, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_0_O_BCLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_0_I_RXD, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_1_O_nSEL_1, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_1_O_nSEL_0, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_1_O_TXD, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_1_O_BCLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SSIC_1_I_RXD, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_HSYNC, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_VSYNC, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_0, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_1, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_2, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_3, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_4, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_5, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_6, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_7, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_8, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_9, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_10, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_11, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_12, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_13, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_14, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_IB_DEV_0_DATA_15, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SYS_O_MON_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_0_O_TX_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {MSHC_1_O_TX_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_RX_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_IB_TX_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_O_TX_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {EQOSC_O_REF_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {VIC_O_REF_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {I2CC_0_IO_SCL, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {I2CC_0_IO_SDA, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {I2SSC_O_TXD, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {I2SSC_IO_TX_BCLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {I2SSC_I_RX_BCLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {I2SSC_I_RX_WS, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {I2SSC_IO_TX_WS, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {I2SSC_I_RXD, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {I2SSC_O_MCLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SYS_I_OSC_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SYS_O_OSC_FEBCLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
    {SYS_O_BASE_CLK, {{"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}, {"N/A"}}}, 
};
