"---------------------------------------------------------------------------
" Chance's .vimrc
"---------------------------------------------------------------------------

" profile start profile.txt
" profile file ~/.vim/rc/*
" profile func dein#*

if &compatible
  set nocompatible
endif

"---------------------------------------------------------------------------
source ~/.vim/rc/dein.rc.vim
source ~/.vim/rc/mappings.rc.vim
source ~/.vim/rc/options.rc.vim

if has('nvim')
  source ~/.vim/rc/neovim.rc.vim
endif

"---------------------------------------------------------------------------

set cscopetag
set cscopeprg='gtags-cscope'
let GtagsCscope_Auto_Load = 1
let GtagsCscope_Auto_Map = 1
let GtagsCscope_Quiet = 1

source ~/.vim/rc/gtags.vim
source ~/.vim/rc/gtags-cscope.vim

" TMUX --------------------------------------------------------- "
if !has('nvim')
if exists('$TMUX')
  set term=screen-256color
endif
endif

